services:
  - type: web
    name: cibernet-backend
    runtime: docker
    plan: free
    region: oregon
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: dev
      - key: DB_URL
        value: jdbc:postgresql://dpg-d2ohcvfdiees73fea0e0-a.oregon-postgres.render.com:5432/alexandra_3fiq
      - key: DB_USER
        value: alexandra
      - key: DB_PASSWORD
        value: aj9xesHMK241spJ1vtJIM7M9C4Y7UfMJ
